### ISSUE TITLE
Assemble index/guide to work so far

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#105]
For right now, we're assembling the index [here](https://docs.google.com/spreadsheets/d/1DbOFQ2pO8RqVJHtcnat196pz9bXVQ_8I8UIi8bcAdhY/edit?gid=0#gid=0).

We will likely break this out into a separate spreadsheet when done.

**Comment by alia-salim** [comment]
@christophermather Just a note that I've added all the content artifacts to the index. Let me know if there's anything else I can help with on this!

**Comment by christophermather** [comment]
Amazing! Thank you.
