### ISSUE TITLE
Keep working to get a development environment at FS

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#20]

**Comment by neilmb** [comment]
Need to answer mission-related questions for cloud team at FS CIO.

**Comment by christophermather** [comment]
@neilmb - any update here? 

If "done", could you add some details about what was completed? And then move to done + closed?

Also: are there any immediate next steps we should articulate for our next sprint?

**Comment by neilmb** [comment]
I think we should mark this as somewhere between "complete" and "won't do". We won't be able to get access and make a meaningful contribution in that environment in the time remaining to our team, so I think we should mark this issue as done.

If we want to track future work for a team on this, we should probably make an epic for something like "Get an environment that can run code at Forest Service".

**Comment by christophermather** [comment]
Closing as "won't do"
