### ISSUE TITLE
Share project deliverables, artifacts, things we've produced

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#32]
@dluetger, @neilmb and @christophermather need to share project artifacts, deliverables, things we've produced with @alia-salim so she can start some review and make recommendations on structuring our project wiki.

This is related to #31

**Comment by christophermather** [comment]
Here's a [spreadsheet of deliverables](https://docs.google.com/spreadsheets/d/1DbOFQ2pO8RqVJHtcnat196pz9bXVQ_8I8UIi8bcAdhY/edit?gid=0#gid=0) to date!

@neilmb and @dluetger, please add anything that I'm missing.

**Comment by neilmb** [comment]
LGTM, marking this as "Done".
