### ISSUE TITLE
Reach out to lands contacts

### ISSUE THREAD

**Issue by dluetger** [18F/usfs-special-uses-prototype#47]

**Comment by dluetger** [comment]
Reached out to the three we had; two responded and it's likely we'll talk to them next week.

**Comment by dluetger** [comment]
Two scheduled, both with our FS SMEs, and two I'm waiting on responses from.

**Comment by christophermather** [comment]
@dluetger - any update here? Have all interviews been scheduled and completed?

If so, could you move to done + closed?

**Comment by dluetger** [comment]
All reached out to, awaiting response from final two.
