### ISSUE TITLE
Future business development

### ISSUE THREAD

**Issue by neilmb** [18F/usfs-special-uses-prototype#49]

**Comment by christophermather** [comment]
@neilmb - I know we discussed sensitivity around this issue. If and when appropriate, could you add details here?

If not appropriate to share details, could we make a decision about whether this issue should come with us into sprint 3?

**Comment by neilmb** [comment]
The project work on this could wrap up soon as it moves on to other parts of the agreements process, so I'd love to keep it open for just one more sprint.

**Comment by christophermather** [comment]
@neilmb - at your discretion... is this done? If so, please close and change to "done".

**Comment by neilmb** [comment]
The separate work on this is done for now.
