### ISSUE TITLE
Question: where do we prototype? Is Cloud.gov viable?

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#52]
We want to make sure that the technical prototyping work that we are doing in this phase is ready to have impact on future work. Should we continue on our Cloud.gov static HTML/CSS site work or should we keep trying to pivot back into the USFS ePermits environment/codebase if we can get access to that code and eventually to a cloud environment there to run the code?

**Comment by neilmb** [comment]
Our static HTML and CSS site, templated by the static site generator 11ty is completely portable and our Github repository is publicly available, so any work we do here on this platform should be very easily translatable onto Forest Service's other computing platforms. Given the challenges getting access to FS computing resources, I think that we should keep prototyping with what we have right now and leave this repo as the starting point for future development efforts at FS.
