### ISSUE TITLE
Review architecture set-up for best practices

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#53]
We discussed the odds and ends that come up in engineering work. We want to make sure that our engineering environment is embodying the characteristics that we want to see.

- Security scanning
- Automated accessibility testing
- Automated unit testing (might not be relevant?)
- Automated integration testing
- Code quality checks
- Branch protection rules
- PR approval rules?
- Tests passing rules?

**Comment by neilmb** [comment]
Discussed this with our Engineering Practices Guild and got some consensus that the remaining things we don't have are

- Security scanning

I'll make a ticket to add it.
