### ISSUE TITLE
Decision: where does our guidance for proponents begin?

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#55]

**Comment by alia-salim** [comment]
I

**Comment by alia-salim** [comment]
Summary of my earlier conversation with Neil about this is [in our running notes doc here (August 8)](https://docs.google.com/document/d/1uCe4Bx91J-0dRt1lWi4a1NCVCMnOcJsu93q4otYNy7E/edit#heading=h.f8lln48llbz3).

**Comment by alia-salim** [comment]
Very rough draft of a "decision record" (including notes from our meeting with SMEs today) [here](https://docs.google.com/document/d/1rjyr6xDBuvJzGiCV6Y8Z5kWWzr3XrNTDAVFzKwlAncI/edit).

**Comment by christophermather** [comment]
Let's discuss this during standup today.

Questions:
- Is our decision decision-ed?
- Sub-question, per yesterday's chat: is it scoped to be in some state of "done" by conclusion of this engagement?
- What are our immediate next steps?

**Comment by christophermather** [comment]
Decision is decisioned!

We'll talk scope + next steps in sprint planning today.
