### ISSUE TITLE
Create a map of proponent's questions as they move through the start of the process

### ISSUE THREAD

**Issue by neilmb** [18F/usfs-special-uses-prototype#59]
In service of the decision in #55

**Comment by alia-salim** [comment]
[Draft of this here](https://app.mural.co/t/gsa6/m/gsa6/1723218133366/fc598453fc3f3260b9c9712fcc905fcbe6880ce1?sender=u9ac43edf54de743b3d9b2405) -- this is intended mostly to keep *myself* organized, and as a discussion aid for #55, but feedback/edits welcome.

**Comment by alia-salim** [comment]
Discussed with SMEs on a call 8/20 -- see #55 . 

I may edit or annotate [the map](https://app.mural.co/t/gsa6/m/gsa6/1723218133366/fc598453fc3f3260b9c9712fcc905fcbe6880ce1?sender=u9ac43edf54de743b3d9b2405) if anything comes up in interviews to change things, but I think it's OK to consider this "done" for its intended purpose.
