### ISSUE TITLE
Map "who" questions

### ISSUE THREAD

**Issue by alia-salim** [18F/usfs-special-uses-prototype#85]
What "who" questions does our prototype need to ask the user, and in what order? How would our plain-language versions of these questions map to the questions on SF-299? What questions apply to only some users?

**Comment by alia-salim** [comment]
[Map on Mural here.](https://app.mural.co/t/gsa6/m/gsa6/1724874448184/3088b05b720a9ca36b74d5d121e2054322372262?sender=u9ac43edf54de743b3d9b2405)

**Comment by christophermather** [comment]
This is currently "in review". What do we need to do in order to move it to "done"? 

This may involve our planned discussion at 1:30pm ET today.
