### ISSUE TITLE
Draft "who" section copy

### ISSUE THREAD

**Issue by alia-salim** [18F/usfs-special-uses-prototype#86]
Provide working copy for the "who" section: questions, options, explainer text, etc.
```[tasklist]
### Tasks
- [ ] https://github.com/18F/usfs-special-uses-prototype/issues/90
```

**Comment by alia-salim** [comment]
In progress [here](https://docs.google.com/document/d/11tK5_3hSFqG27mDv3OySOMHZN9tAjso_5nk_lOLKHaU/edit).

**Comment by christophermather** [comment]
@alia-salim - is it possible to consider this "done" in the sense that a draft of "who" section copy exists?

If so, two requests:

1. Can you articulate a follow-on task? 
2. Can you close this and mark it as "done"?

**Comment by christophermather** [comment]
Our FS friends are going to see if they can dig up some resources to help this work.

**Comment by christophermather** [comment]
This is "done" for our purposes. See these links:

- ["who" copy](https://docs.google.com/document/d/11tK5_3hSFqG27mDv3OySOMHZN9tAjso_5nk_lOLKHaU/edit)
- [version flow in Mural](https://app.mural.co/t/gsa6/m/gsa6/1726172559221/fde0b6672ae842ac183c6208be5394e957455714?sender=u9ac43edf54de743b3d9b2405)
