### ISSUE TITLE
Find working definitions for explainer copy

### ISSUE THREAD

**Issue by christophermather** [18F/usfs-special-uses-prototype#90]
This is basically a sub-task of #86 

Some definitions of terms have proven elusive/non-intuitive. @alia-salim is going to do some work to track these down. We've also engaged our FS friends to locate some resources that may assist with these definitions.

**Comment by alia-salim** [comment]
Closing this because the draft copy now has working definitions good enough to move forward with. If/when we present or hand off the prototype, we should note that all copy is FPO.
